Move pdfminer to commown_website_sale_coupon and pin its version
[CI] Pin pdfminer.six version to 20220319 as more recent versions require too modern cryptography

attachment_indexation requires pdfminer and advices to install pdfminer.six
(which is the maintained fork of pdfminer). However, recent pdfminer.six
version require cryptography>=36.0.0 which is not compatible with pyOpenSSL
20.0.1 which is installed on Ubuntu 22.04 (generates CI error: module 'lib'
has no attribute 'X509_V_FLAG_NOTIFY_POLICY', see PR 8769 of pyca/cryptography
on github).