Fix task create crash
The @api.model decorator was missing, leading to an incorrect call from the UI
and a crash with following error:
TypeError: create() missing 1 required positional argument: 'values'

Fixes issue id=5836.