[pre-commit] Update oca maintainer-tools to fix a CI crash
The traceback was:

An unexpected error has occurred: CalledProcessError: command: ('/home/runner/.cache/pre-commit/repo9ofo_le2/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/runner/.cache/pre-commit/repo9ofo_le2
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'

stderr:
      error: subprocess-exited-with-error

      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [33 lines of output]
          /home/runner/.cache/pre-commit/repo9ofo_le2/py_env-python3/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
            warnings.warn(
          /home/runner/.cache/pre-commit/repo9ofo_le2/.eggs/vcs_versioning-2.2.1-py3.10.egg/vcs_versioning/_backends/_git.py:426: UserWarning: "/home/runner/.cache/pre-commit/repo9ofo_le2" is shallow and may cause errors
            pre_parse(wd)
          running egg_info
          creating /tmp/pip-pip-egg-info-44zo0mvo/oca_maintainers_tools.egg-info
          writing /tmp/pip-pip-egg-info-44zo0mvo/oca_maintainers_tools.egg-info/PKG-INFO
          writing dependency_links to /tmp/pip-pip-egg-info-44zo0mvo/oca_maintainers_tools.egg-info/dependency_links.txt
          writing entry points to /tmp/pip-pip-egg-info-44zo0mvo/oca_maintainers_tools.egg-info/entry_points.txt
          writing requirements to /tmp/pip-pip-egg-info-44zo0mvo/oca_maintainers_tools.egg-info/requires.txt
          writing top-level names to /tmp/pip-pip-egg-info-44zo0mvo/oca_maintainers_tools.egg-info/top_level.txt
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/home/runner/.cache/pre-commit/repo9ofo_le2/setup.py", line 11, in <module>
              setuptools.setup(
            File "/home/runner/.cache/pre-commit/repo9ofo_le2/py_env-python3/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
              return distutils.core.setup(**attrs)
            File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
              dist.run_commands()
            File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
              self.run_command(cmd)
            File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
              cmd_obj.run()
            File "/home/runner/.cache/pre-commit/repo9ofo_le2/.eggs/setuptools_scm-10.2.0-py3.10.egg/setuptools_scm/_integration/egg_info.py", line 119, in run
              super().run()
            File "/home/runner/.cache/pre-commit/repo9ofo_le2/py_env-python3/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 299, in run
              self.find_sources()
            File "/home/runner/.cache/pre-commit/repo9ofo_le2/.eggs/setuptools_scm-10.2.0-py3.10.egg/setuptools_scm/_integration/egg_info.py", line 106, in find_sources
              mm.ignore_egg_info_dir = self.ignore_egg_info_in_manifest  # type: ignore[attr-defined]
            File "/usr/lib/python3.10/distutils/cmd.py", line 103, in __getattr__
              raise AttributeError(attr)
          AttributeError: ignore_egg_info_in_manifest
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.

Check the log at /home/runner/.cache/pre-commit/pre-commit.log
Error: Process completed with exit code 3.